
services:
  - docker:dind

include:
  - template: Jobs/Test.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Build.gitlab-ci.yml

variables:
  CODE_QUALITY_DISABLED: true
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

test:
  image: gradle:8.3.0-jdk17-alpine
  script: ./gradlew test
  allow_failure: true
